# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Launches a KinD cluster to deploy our application under test to
    - name: Launch Cluster
      uses: engineerd/setup-kind@v0.3.0
    
    # Basic check that the cluster is up and running
    - name: Test cluster
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system

    # Deploy the application we want to scan to the cluster in a separate, new namespace
    - name: Deploy application to cluster
      run: |
        kubectl create namespace webgoat
        kubectl run --generator=run-pod/v1 webgoat --image=webgoat/webgoat-7.1 -n webgoat

    # Kick off the scan with Alcide Advisor
    - name: Scan Cluster
      uses: alcideio/advisor-action@v1.1.0   
      with:
        include_namespaces: 'webgoat'
        output_file: 'advisor-scan.html'

    # Upload the report to GitHub Action Artifacts
    - name: Upload Alcide Advisor Scan Report
      uses: actions/upload-artifact@v1
      with:
        name: advisor-scan.html
        path: advisor-scan.html
